name: '📝 Documentation'
description: 'Adding or improving in docs'
title: '[DOC]: '
labels:
  - documentation
body:
  - type: textarea
    attributes:
      label: Suggested Changes
      description: What would you like to see happen in the docs?
    validations:
      required: true